#!/bin/bash
#
#
# we can be called with the following arguments (6.5 of Debian policy):
#  install:          (our version): install our version
#  upgrade:          (our version): upgrade to our version
#  abort-upgrade:    (old version): upgrade to a new version failed

# defaults
[ -r /etc/default/ems-bus ] && . /etc/default/ems-bus

if [ "$1" = "install" -o "$1" = "upgrade" ]; then

  # Para o serviço pre instalado
  systemctl stop ems-bus.service 2>/dev/null || true	

fi



