#!/bin/bash
#
#
# we can be called with the following arguments (6.5 of Debian policy):
#  install:          (our version): install our version
#  upgrade:          (our version): upgrade to our version
#  abort-upgrade:    (old version): upgrade to a new version failed

# defaults
[ -r /etc/default/ems-bus ] && . /etc/default/ems-bus

if [ "$1" = "install" -o "$1" = "upgrade" ]; then

	# pare e desative o serviço systemctl
	systemctl stop ems-bus.service 2>/dev/null && sleep 4 || true	
	rm -f /etc/systemd/system/ems-bus.service
	systemctl disable ems-bus.service 2>/dev/null || true	
	systemctl daemon-reload 2>/dev/null || true	

	# clean
	echo "Apagando instalação anterior..."
	rm -Rf /usr/lib/ems-bus
	rm -f /etc/ems-bus


	# remove user
	delgroup erlangms > /dev/null || true
  

fi



