#!/bin/sh

#
# we can be called with the following arguments (6.5 of Debian policy):
#  upgrade:          (new version): upgrade to a new version
#  failed-upgrade:   (our version): failed to upgrade
#  remove:           (our version): remove this package
#  deconfigure:      (our version): removing conflicting version

# defaults
[ -r /etc/default/ems-bus ] && . /etc/default/ems-bus

. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup


exit 0
