#!/bin/sh
#
# we can be called with the following arguments (6.5 of Debian policy):
#  configure:         (our version): installing/configuring new version
#  abort-upgrade:     (old version): upgrading to a new version failed
#  abort-remove:      (our version): removing this package failed
#  abort-deconfigure: (our version): error during resolving conflicts

## @todo Do we really gain anything from not just executing everything
##       unconditionally?

LOG="/var/log/ems-bus/ems-bus.log"
USER_EMS_BUS=erlangms
GROUP_EMS_BUS=erlangms

# defaults
[ -r /etc/default/ems-bus ] && . /etc/default/ems-bus


if [ "$1" = "configure" ]; then

  # database and log path
  mkdir -p /usr/lib/ems-bus/priv/db > /dev/null 2>&1
  mkdir -p /var/log/ems-bus > /dev/null 2>&1

  # create users and groups
  groupadd --system  $GROUP_EMS_BUS
  password="admin"
  #password_crypt=$(perl -e 'print crypt($ARGV[0], "wtf")' $password)
  password_crypt="wtdgpkEyPdF1A"
  useradd -g $GROUP_EMS_BUS --no-create-home --system \
						    --home-dir /usr/lib/ems-bus/ \
						    --shell /bin/bash \
						    --password $password_crypt \
						    --comment "User do barramento Erlangms ems-bus" $USER_EMS_BUS

  # change owners
  chown -Rf $USER_EMS_BUS:$GROUP_EMS_BUS /usr/lib/ems-bus
  chown -Rf $USER_EMS_BUS:$GROUP_EMS_BUS /etc/ems-bus
  chown -f $USER_EMS_BUS:$GROUP_EMS_BUS /usr/bin/ems-bus
  chown -Rf $USER_EMS_BUS:$GROUP_EMS_BUS /var/log/ems-bus


  # The starters need to be Suid root.
  if ! dpkg-statoverride --list /usr/lib/ems-bus/bin/ems-bus > /dev/null 2>&1; then
    chmod 4777 /usr/lib/ems-bus/bin/ems-bus
  fi
  # The starters need to be Suid root para Erts.
  for ExecutableErts in `find /usr/lib/ems-bus/erts-*/bin/`; do
    if ! dpkg-statoverride --list $ExecutableErts > /dev/null 2>&1; then
      chmod 4511 $ExecutableErts
    fi
  done
  
  # Cria a pasta /var/log/ems-bus
  mkdir -p /var/log/ems-bus
  chown -Rf $USER_EMS_BUS:$GROUP_EMS_BUS /var/log/ems-bus

  # systemd
  chown -hf  $USER_EMS_BUS:$GROUP_EMS_BUS /etc/systemd/system/ems-bus.service
  systemctl enable ems-bus.service  > /dev/null 2>&1 || true
  systemctl daemon-reload  > /dev/null 2>&1 || true
  
  
fi



systemctl start ems-bus.service  > /dev/null 2>&1 || true

exit 0
